name: CI
on: [pull_request, push]
jobs:
  build:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        name: Install
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Lint
        with:
          cmd: lint
      - uses: borales/actions-yarn@v3.0.0
        name: Test
        with:
          cmd: test
